#docker build -f src/main/docker/Dockerfile -t app-authors .
#docker build -f src/main/docker/Dockerfile -t joelespinosa/app-authors .
#ejemplo del repo de redhat //.docker build -f src/main/docker/Dockerfile -t quay.io/joelespinosa/app-authors:1.0.0 .
#docker push joelespinosa/app-authors
FROM eclipse-temurin:21.0.9_10-jre-alpine-3.23

ENV LANGUAGE="en_US:en"

RUN mkdir /app
WORKDIR /app

COPY build/quarkus-app/lib ./lib
COPY build/quarkus-app/quarkus ./quarkus
COPY build/quarkus-app/app ./app
COPY build/quarkus-app/quarkus-run.jar app.jar

CMD ["java", "-jar", "app.jar"]