
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-authors
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-authors
  template:
    metadata:
      labels:
        app: app-authors
    spec:
      containers:
        - name: app-authors
          image: joelespinosa/app-authors:latest
          ports:
            - containerPort: 5432
          imagePullPolicy: Always
          env:
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: jdbc:postgresql://dbserver:5432/distribuida
            - name: QUARKUS_DATASOURCE_USERNAME
              value: postgres
            - name: QUARKUS_DATASOURCE_PASSWORD
              value: postgres
            - name: QUARKUS_HTTP_PORT
              value: "8080"
            - name: CONSUL_HOST
              value: consul
            - name: CONSUL_PORT
              value: "8500"
            - name:  QUARKUS_FLYWAY_ACTIVE
              value: "true"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: app-authors-service
spec:
  type: ClusterIP
  selector:
    app: app-authors
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080