quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=BioEvolt#4e
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/books



quarkus.http.port=8070
quarkus.http.host=0.0.0.0

consul.host=127.0.0.1
consul.port-=8500

quarkus.flyway.active=true
quarkus.flyway.baseline-at-start=true
quarkus.flyway.migrate-at-start=true

quarkus.container-image.username=joelespinosa
quarkus.container-image.tag=1.0.0