quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=BioEvolt#4e
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/books

quarkus.hibernate-orm.log.sql=true

quarkus.http.port=8070