quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=BioEvolt#4e
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/books



quarkus.http.port=8070
quarkus.http.host=0.0.0.0

quarkus.stork.authors-api.service-discovery.type=consul
quarkus.stork.authors-api.service-discovery.consul-host=${consul.host}
quarkus.stork.authors-api.service-discovery.consul-port=${consul.port}
quarkus.stork.authors-api.service-discovery.application=app-prestamos
quarkus.stork.authors-api.service-discovery.refresh-period=5s

consul.host=127.0.0.1
consul.port-=8500